moddef::moddef!(
    flat(pub) mod {
        container_or_single,
        container,
        into_list,
        list_or_single,
        list,
        lists_or_single,
        lists,
        matrix_or_single,
        matrix,
        maybe_container,
        maybe_list,
        maybe_lists,
        maybe_matrix,
        maybe_owned_list,
        maybe_owned_lists,
        maybe_owned_matrix,
        owned_list_or_single,
        owned_list,
        owned_lists,
        owned_matrix,
        polynomial,
        product_sequence,
        sum_sequence
    }
);