moddef::moddef!(
    flat(pub) mod {
        czt,
        dct_2d,
        dct,
        dft_2d,
        dft,
        dht,
        dst_2d,
        dst,
        dwht,
        dwt,
        hilbert_2d,
        hilbert,
        iczt,
        idft_2d,
        idft,
        idht,
        idwht,
        sdft_kw,
        sdft,
        stft,
        swift
    }
);