moddef::moddef!(
    flat(pub) mod {
        bilinear,
        dct,
        dft,
        dftmtx,
        dht,
        hilbert_transform,
        hilbert,
        idct,
        iwht,
        sftrans,
        to_sos,
        to_ss,
        to_tf,
        to_zpk,
        wht
    }
);