moddef::moddef!(
    flat(pub) mod {
        cconv,
        conv,
        conv_2d,
        decimate,
        decode,
        downsample,
        encode,
        fftfilt,
        filter_mut,
        filter,
        filtfilt,
        interp,
        normalize,
        qmf,
        resample,
        sgolayfilt,
        upsample,
        upsample_fill,
        window
    }
);