moddef::moddef!(
    flat(pub) mod {
        cceps,
        cohere,
        filternorm,
        filtic,
        filtord,
        findpeaks,
        freqs,
        freqz,
        fwhm,
        grpdelay,
        impz,
        isallpass,
        ismaxphase,
        isminphase,
        isstable,
        movingrms,
        real_freqz,
        real_specgram,
        specgram,
    }
);